### ISSUE TITLE
I just set up a server and...

### ISSUE THREAD

**Issue by Venus5687** [Savefade/SimpleTwitterServer#1]
I'm getting a 500 Internal Server Error every time I try to sign up.
I had to guess the instructions since there weren't any.
I'm using Charles with the root certificate and the rewrite feature.
And XAMPP for the server.
(iPhone 4S, iOS 6.1.3, Twitter 4.1.1)
![500 Internal Server Error](https://github.com/user-attachments/assets/a95d89e4-4bd6-4d6d-8edc-63b2bc2ff0fb)

**Comment by Savefade** [comment]
The issue is likely a broken .htaccess file. See if you can access localhost normally.

**Comment by Venus5687** [comment]
I can access localhost normally.
This is my .htaccess file.
```
RewriteEngine On
RewriteBase /
RewriteRule ^oauth/(.+)$ API/Oauth/$1.php [L]
RewriteRule ^mobile_client_api/(.+)$ API/MobileClientAPI/$1.php [L]
RewriteRule ^1/account/generate.json$ API/v1/Account/Generate.php [L]

RewriteRule ^1.1/statuses/home_timeline.json$ API/v1/Statuses/Timeline.php [L]
RewriteRule ^1/statuses/home_timeline.json$ API/v1/Statuses/Timeline.php [L]
RewriteRule ^1.1/statuses/user_timeline.json$ API/v1.1/Statuses/User_Timeline.php [L]
RewriteRule ^1.1/statuses/update.json$ API/v1/Statuses/Update.php [L]
RewriteRule ^1/statuses/update.json$ API/v1/Statuses/Update.php [L]
RewriteRule ^1/users/(\d+).json$ API/v1/Users/$1.php [L]

RewriteRule ^(.+)/account/verify_credentials.json$ API/v1.1/account/verify_credentials.php [L]

RewriteRule ^1.1/search/typeahead.json$ API/v1.1/Search/TypeAhead.php [L]
RewriteRule ^1.1/search/universal.json$ API/v1.1/Search/TypeAhead.php [L]
RewriteRule ^1.1/users/show.json$ API/v1.1/Users/Profile.php [L]
```
(I didn't edit the file)

**Comment by Savefade** [comment]
What version of PHP and Apache are you using?

**Comment by Venus5687** [comment]
Apache/2.4.56 (Unix) OpenSSL/1.1.1t PHP/8.0.28 mod_perl/2.0.12 Perl/v5.34.1

**Comment by Venus5687** [comment]
Also, I've noticed that the code on GitHub is from November, but the code from the live demo is from December.
Have you updated the code on GitHub?

**Comment by Savefade** [comment]
It's the same code. I started hosting the demo this month. Can you delete all of the rules and see if that fixes the error. You are going to get 404 though.

**Comment by Savefade** [comment]
Can you also try putting this ( php_flag display_errors 1 ) on top of .htaccess

**Comment by Venus5687** [comment]
<br />
<b>Warning</b>:  include(../../../Config/DatabaseConnection.php): Failed to open stream: No such file or directory in <b>/Applications/XAMPP/xamppfiles/htdocs/Library/LoginFunctions.php</b> on line <b>20</b><br />
<br />
<b>Warning</b>:  include(): Failed opening '../../../Config/DatabaseConnection.php' for inclusion (include_path='.:/Applications/XAMPP/xamppfiles/lib/php') in <b>/Applications/XAMPP/xamppfiles/htdocs/Library/LoginFunctions.php</b> on line <b>20</b><br />
<br />
<b>Warning</b>:  Undefined variable $DBReq in <b>/Applications/XAMPP/xamppfiles/htdocs/Library/LoginFunctions.php</b> on line <b>22</b><br />
<br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function prepare() on null in /Applications/XAMPP/xamppfiles/htdocs/Library/LoginFunctions.php:22
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/API/MobileClientAPI/signup.php(15): GetUserData('testing')
#1 {main}
  thrown in <b>/Applications/XAMPP/xamppfiles/htdocs/Library/LoginFunctions.php</b> on line <b>22</b><br />

**Comment by Venus5687** [comment]
I'm gonna fix it real quick.

**Comment by Savefade** [comment]
just replace ../../../ with "$_SERVER['DOCUMENT_ROOT'] . "

**Comment by Venus5687** [comment]
<br />
<b>Warning</b>:  Undefined variable $verifyNewUsers in <b>/Applications/XAMPP/xamppfiles/htdocs/Library/LoginFunctions.php</b> on line <b>57</b><br />
<br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function bind_param() on bool in /Applications/XAMPP/xamppfiles/htdocs/Library/LoginFunctions.php:58
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/API/MobileClientAPI/signup.php(24): RegisterNewAccount('testing', 'testing', 'i'm not sharing my email', '$2y$10$wOjKfMV....', '9ba1b5bd1b60112...', '03aca0d21b77721...')
#1 {main}
  thrown in <b>/Applications/XAMPP/xamppfiles/htdocs/Library/LoginFunctions.php</b> on line <b>58</b><br />

**Comment by Savefade** [comment]
I forgot to update the users config file. To fix this error just paste this into users.php "$verifyNewUsers = false;"

**Comment by Venus5687** [comment]
<br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function bind_param() on bool in /Applications/XAMPP/xamppfiles/htdocs/Library/LoginFunctions.php:58
now this error remains

**Comment by Venus5687** [comment]
I think this error means that it's searching for undefined tables in the database.

**Comment by Savefade** [comment]
did you setup your mysql db?

**Comment by Venus5687** [comment]
Yeah.
![Schermata 2024-12-15 alle 14 08 26](https://github.com/user-attachments/assets/7b666a38-ad88-45d4-af13-83ee7ab37787)

**Comment by Savefade** [comment]
The name of the table should be lower case and these are the values which need to be present in the table (`ID`, `Username`, `FullName`, `Email`, `IsVerified`, `Password`, `Salt`, `Token`, `RegistrationTS`)

**Comment by Savefade** [comment]
I didnt update the db lol.

**Comment by Venus5687** [comment]
Is this OK?
![Schermata 2024-12-15 alle 14 13 18](https://github.com/user-attachments/assets/4ba4373d-3c9f-4fc4-a598-68fac8b9d946)

**Comment by Savefade** [comment]
Yes

**Comment by Venus5687** [comment]
It's throwing out the same error
<br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function bind_param() on bool in /Applications/XAMPP/xamppfiles/htdocs/Library/LoginFunctions.php:58

**Comment by Savefade** [comment]
hmm.. It being a bool means that the sql staement is not valid. Try executing the prepared statement on line 57 (Don't forget to change the values)

**Comment by Venus5687** [comment]
maybe this is causing it
$verifyNewUsers = false;
because I tried it without this boolean and it worked

**Comment by Venus5687** [comment]
yup that was causing it.
I just set verifynewusers to true and it signed up

**Comment by Venus5687** [comment]
the only problem is that update.json gives 401 everytime
(so when I tweet it says Error: not authorized)

**Comment by Savefade** [comment]
Are you sure your client is providing the oauth token when you request that endpoint?

**Comment by Venus5687** [comment]
It's not (just checked). Should I try an older client?
![Schermata 2024-12-15 alle 14 40 11](https://github.com/user-attachments/assets/7c6a5c16-b5dd-4444-b0ad-fa0be78511df)

**Comment by Savefade** [comment]
Are you using an iPad?

**Comment by Venus5687** [comment]
No. I'm using an iPhone 4S with iOS 6.

**Comment by Savefade** [comment]
Try a newer version (rec: 5.X)

**Comment by Venus5687** [comment]
Okay.

**Comment by Venus5687** [comment]
It's not giving the token.
![Schermata 2024-12-15 alle 14 51 33](https://github.com/user-attachments/assets/02fe233b-2350-4155-9e51-98d90d8dca28)

**Comment by Savefade** [comment]
Log out and log back in

**Comment by Venus5687** [comment]
Same thing :(
![IMG_0042](https://github.com/user-attachments/assets/2e8cd523-b246-4a78-9f31-824b44ec4ffd)
(it means Tweet not sent)

**Comment by Venus5687** [comment]
Okay, now it sent the token but it still gives me a 401.
![Schermata 2024-12-15 alle 16 44 59](https://github.com/user-attachments/assets/8f8c39bc-82eb-4e8b-b2aa-2c1df0cb7074)
![Schermata 2024-12-15 alle 16 47 11](https://github.com/user-attachments/assets/1ecd3b5b-5a85-4a70-8fa6-2d0a78f73957)

**Comment by Savefade** [comment]
401 means that your token might me invalid

**Comment by Venus5687** [comment]
I don't know why but Twitter 5.0.1 is not sending a token to the "home_timeline" at all and Twitter 4.1 sometimes sends invalid tokens (I think).

**Comment by Savefade** [comment]
I personally use this version when testing. https://mtmdev.org/forum/index.php?threads/twitter-5-12-version-spoofed.3170/

**Comment by Venus5687** [comment]
![Schermata 2024-12-15 alle 17 28 53](https://github.com/user-attachments/assets/6ff04b3f-b3bd-4980-8d54-cc37cf50998e)
I think this version uses "home.json" to load the timeline. Should I rewrite it to "User_Timeline.php"?

**Comment by Venus5687** [comment]
When Twitter 5.2+ try to load the timeline, they crash. I don't know why.

**Comment by Savefade** [comment]
Sorry i completely forgot that for some reason twitter chose to use different endpoint for timelines on iPhone (which is not implemented, yet. Lacks documentation) . I use an iPad for testing (which requests its own endpoint). Also were you able to post anything?

**Comment by Venus5687** [comment]
Hi. A little update. Tweets now post correctly with the IPA you sent me. But, user_timeline.json results in a "500 Internal Server Error".
![Schermata 2024-12-19 alle 21 14 35](https://github.com/user-attachments/assets/948997fd-9873-4430-af2b-0d0c7eb29f3c)
Also, Twitter 5.11+ (including the IPA you sent me) log out every time the device locks and the app closes. (but the account still remains as I saw in the Twitter iOS Settings)

**Comment by Venus5687** [comment]
UPDATE: Twitter 5.7 works properly.

**Comment by Venus5687** [comment]
I haven't seen any problems yet, so I'm gonna close this issue.
